name: Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: make clean bin/ccomp test
